development:
  adapter: postgresql
  database: shelfesteem_development
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: shelfesteem_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: shelfesteem_production
  pool: 5
  timeout: 5000
